### ISSUE TITLE
getting stats for particular timegap

### ISSUE THREAD

**Issue by anieruddha** [solidfire/solidfire-sdk-python#4]
Hi,

Is it possible to get volumn stats for particular time difference like for last hour, last 24 hours etc

Thanks

**Comment by dalepa** [comment]
Anyone also working on a harvest collector for solidfire?

**Comment by jason-womack** [comment]
The current version of the SolidFire SDK's, only offers a mapping of the most used SolidFire API services.  The next version will reach service coverage parity with Nitrogen and Oxygen (7/8) and after that, Florine (9).  

Once development has reached that point, we will begin investigating additional business logic.

While the instantaneous Volume Stats is implemented for the SDK, since the API does not offer historical Volume Stats, neither will the SDK at this time.  

Still, with the Volume Stats Service, one could implement a historical tracker that would query the cluster on regular intervals (daily, hourly, every 5 minutes) and store those values for processing as a timeseries.

I hope this helps.
